-- Migration: Add roles and caretaker-elder relationship
-- Role types: 'caretaker', 'elder', 'elder_self'

-- 1. Add role column to profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS role TEXT CHECK (role IN ('caretaker', 'elder', 'elder_self'));

-- 2. Create caretaker_elder_links table
CREATE TABLE IF NOT EXISTS public.caretaker_elder_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caretaker_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  elder_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  UNIQUE(caretaker_id, elder_id)
);

ALTER TABLE public.caretaker_elder_links ENABLE ROW LEVEL SECURITY;

-- 3. Caretaker-Elder Link Policies
CREATE POLICY "Caretakers can see their links" 
ON public.caretaker_elder_links FOR SELECT 
USING (auth.uid() = caretaker_id OR auth.uid() = elder_id);

-- 4. Helper function to check if a user is a caretaker of an elder
CREATE OR REPLACE FUNCTION public.is_caretaker_of(elder_id_param UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.caretaker_elder_links
    WHERE caretaker_id = auth.uid() AND elder_id = elder_id_param
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Update RLS for health modules to allow caretakers access
-- Todos
DROP POLICY IF EXISTS "Users can manage own todos" ON public.todos;
CREATE POLICY "Users can manage own todos" ON public.todos 
FOR ALL USING (auth.uid() = user_id OR public.is_caretaker_of(user_id));

-- Medicines
DROP POLICY IF EXISTS "Users manage own medicines" ON public.medicines;
CREATE POLICY "Users manage own medicines" ON public.medicines 
FOR ALL USING (auth.uid() = user_id OR public.is_caretaker_of(user_id));

-- Water Logs
DROP POLICY IF EXISTS "Users manage own water logs" ON public.water_logs;
CREATE POLICY "Users manage own water logs" ON public.water_logs 
FOR ALL USING (auth.uid() = user_id OR public.is_caretaker_of(user_id));

-- Grocery Items
DROP POLICY IF EXISTS "Users manage own groceries" ON public.grocery_items;
CREATE POLICY "Users manage own groceries" ON public.grocery_items 
FOR ALL USING (auth.uid() = user_id OR public.is_caretaker_of(user_id));

-- Health Logs
DROP POLICY IF EXISTS "Users manage own health logs" ON public.health_logs;
CREATE POLICY "Users manage own health logs" ON public.health_logs 
FOR ALL USING (auth.uid() = user_id OR public.is_caretaker_of(user_id));

-- Appointments
DROP POLICY IF EXISTS "Users manage own appointments" ON public.appointments;
CREATE POLICY "Users manage own appointments" ON public.appointments 
FOR ALL USING (auth.uid() = user_id OR public.is_caretaker_of(user_id));
