-- 1. Create Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  virtual_elder_id UUID REFERENCES public.virtual_elders(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.comments;

-- 3. RLS for Comments
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public see all comments" ON public.comments;
CREATE POLICY "Public see all comments" ON public.comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can comment" ON public.comments;
CREATE POLICY "Anyone can comment" ON public.comments FOR INSERT WITH CHECK (true);

-- 4. Create a View for comment feed with author details
CREATE OR REPLACE VIEW public.comment_feed AS
SELECT 
  c.*,
  COALESCE(pr.display_name, ve.display_name, 'ผู้ใช้งาน') as author_name,
  COALESCE(pr.avatar_url, ve.avatar_url) as author_avatar
FROM public.comments c
LEFT JOIN public.profiles pr ON c.user_id = pr.id
LEFT JOIN public.virtual_elders ve ON c.virtual_elder_id = ve.id;

GRANT SELECT ON public.comment_feed TO anon, authenticated;
