-- Table for Medicine Reminders
CREATE TABLE public.medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  dosage TEXT, -- e.g., '1 เม็ด'
  timing TEXT, -- e.g., 'หลังอาหารเช้า'
  reminder_time TIME, -- Optional specific time
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own medicines" ON public.medicines FOR ALL USING (auth.uid() = user_id);
