-- SOS/Help Alerts
CREATE TABLE IF NOT EXISTS public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  virtual_elder_id UUID REFERENCES public.virtual_elders(id) ON DELETE CASCADE,
  message TEXT DEFAULT 'ต้องการความช่วยเหลือ',
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- Policy: Caretakers can see alerts for their elders
CREATE POLICY "Caretakers see real elder alerts" ON public.alerts
FOR SELECT USING (
  user_id IN (SELECT elder_id FROM public.caretaker_elder_links WHERE caretaker_id = auth.uid())
);

CREATE POLICY "Caretakers see virtual elder alerts" ON public.alerts
FOR ALL USING (
  virtual_elder_id IN (SELECT id FROM public.virtual_elders WHERE caretaker_id = auth.uid())
);

-- Policy: Elders can create alerts
CREATE POLICY "Elders create own alerts" ON public.alerts
FOR INSERT WITH CHECK (auth.uid() = user_id OR virtual_elder_id IS NOT NULL);

-- Family Photos
CREATE TABLE IF NOT EXISTS public.family_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  virtual_elder_id UUID REFERENCES public.virtual_elders(id) ON DELETE CASCADE,
  photo_url TEXT NOT NULL,
  caption TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE public.family_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Elders view family photos" ON public.family_photos
FOR SELECT USING (auth.uid() = user_id OR virtual_elder_id IS NOT NULL);

CREATE POLICY "Caretakers manage family photos" ON public.family_photos
FOR ALL USING (
  user_id IN (SELECT elder_id FROM public.caretaker_elder_links WHERE caretaker_id = auth.uid()) OR
  virtual_elder_id IN (SELECT id FROM public.virtual_elders WHERE caretaker_id = auth.uid())
);

-- Meal Logs & Calories
CREATE TABLE IF NOT EXISTS public.meal_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  virtual_elder_id UUID REFERENCES public.virtual_elders(id) ON DELETE CASCADE,
  meal_type TEXT, -- 'breakfast', 'lunch', 'dinner', 'snack'
  calories INT DEFAULT 0,
  description TEXT,
  log_date DATE DEFAULT CURRENT_DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE public.meal_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Elders manage meal logs" ON public.meal_logs
FOR ALL USING (auth.uid() = user_id OR virtual_elder_id IS NOT NULL);

CREATE POLICY "Caretakers view meal logs" ON public.meal_logs
FOR SELECT USING (
  user_id IN (SELECT elder_id FROM public.caretaker_elder_links WHERE caretaker_id = auth.uid()) OR
  virtual_elder_id IN (SELECT id FROM public.virtual_elders WHERE caretaker_id = auth.uid())
);
