-- 1. Drop the old invite system
DROP TABLE IF EXISTS public.elder_invites;

-- 2. Create a new "Caretaker Invites" table
-- Caretaker creates a code, Elder enters it during setup.
CREATE TABLE IF NOT EXISTS public.caretaker_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caretaker_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  elder_name TEXT, -- To help caretaker identify who they created it for
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted')),
  elder_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- Filled when elder enters code
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE public.caretaker_invites ENABLE ROW LEVEL SECURITY;

-- 3. Caretakers manage their own invites
CREATE POLICY "Caretakers manage own invites" 
ON public.caretaker_invites FOR ALL 
USING (auth.uid() = caretaker_id);

-- 4. Elders can read invites to find the one they were given
CREATE POLICY "Elders can read invites" 
ON public.caretaker_invites FOR SELECT 
USING (auth.role() = 'authenticated');

-- 5. Elders can "apply" to an invite by updating it with their ID
CREATE POLICY "Elders can apply to invite"
ON public.caretaker_invites FOR UPDATE
USING (auth.role() = 'authenticated')
WITH CHECK (elder_id = auth.uid() AND status = 'pending');
