-- 1. Create a table for invite codes
CREATE TABLE IF NOT EXISTS public.elder_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  elder_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '24 hours') NOT NULL
);

ALTER TABLE public.elder_invites ENABLE ROW LEVEL SECURITY;

-- 2. Elder can create and see their own invites
CREATE POLICY "Elders can manage own invites" 
ON public.elder_invites FOR ALL 
USING (auth.uid() = elder_id);

-- 3. Caretakers can read any invite (to validate the code)
CREATE POLICY "Caretakers can read invites" 
ON public.elder_invites FOR SELECT 
USING (auth.role() = 'authenticated');
