-- 1. Remove Chat (Community Messages)
DROP TABLE IF EXISTS public.messages;

-- 2. Create Diary table
CREATE TABLE public.diaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  mood TEXT, -- 'มีความสุข', 'ปกติ', 'เศร้า', 'ตื่นเต้น'
  entry_date DATE DEFAULT CURRENT_DATE,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS
ALTER TABLE public.diaries ENABLE ROW LEVEL SECURITY;

-- 4. Policies
CREATE POLICY "Users can manage own diaries" ON public.diaries FOR ALL USING (auth.uid() = user_id);
