-- Use 10-character alphanumeric codes for Elders
ALTER TABLE public.virtual_elders ADD COLUMN login_code TEXT UNIQUE;

-- Create broadcast system for Caretakers to send messages to their virtual elders
CREATE TABLE IF NOT EXISTS public.broadcasts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caretaker_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  virtual_elder_id UUID REFERENCES public.virtual_elders(id) ON DELETE CASCADE, -- NULL means broadcast to ALL their virtual elders
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE public.broadcasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Caretakers manage broadcasts" 
ON public.broadcasts FOR ALL 
USING (auth.uid() = caretaker_id);

CREATE POLICY "Elders see broadcasts" 
ON public.broadcasts FOR SELECT 
USING (
  virtual_elder_id IN (SELECT id FROM public.virtual_elders)
  OR virtual_elder_id IS NULL
);
